application: <appid>
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: always

- url: /adminmedia
  static_dir: _generated_media/1/admin_media
  secure: always
  
- url: /media
  static_dir: _generated_media/
  secure: always  

- url: /images
  static_dir: core/static/images
  secure: always

- url: /styles
  static_dir: core/static/styles
  secure: always

- url: /scripts
  static_dir: core/static/scripts
  secure: always

- url: /closure-library-read-only
  static_dir: closure-library-read-only
  secure: always  

- url: /favicon.ico
  static_files: core/static/images/favicon.ico
  upload: favicon.ico
  secure: always

- url: /tasks/.*
  script: main.py

- url: /.*
  script: main.py
  secure: always
